### PR TITLE
feat: Add D'CENT Wall in WalletModal (pancake-uikit)

### PR DESCRIPTION
**Pull request by KyungeunKim**
- [x] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-uikit/blob/master/CONTRIBUTING.md) first
- [x] If your PR is work in progress, open it as `draft`
- [x] Before requesting a review, all the checks need to pass
- [x] Explain what your PR does

**Add D'CENT Wall in WalletModal**

### CODE REVIEW

**Comment by RabbitDoge** [comment]
We don't add wallets on demand like this.

**Comment by paromix** [comment]
> We don't add wallets on demand like this.

Hi @RabbitDoge 
My name is Minho Yoo, Chief Strategy Officer at D'CENT wallet. Thanks for your prompt response.
Please let me know if there is any process or requirement for adding wallet onto your service.

**Comment by RabbitDoge** [comment]
> > We don't add wallets on demand like this.
> 
> Hi @RabbitDoge
> My name is Minho Yoo, Chief Strategy Officer at D'CENT wallet. Thanks for your prompt response.
> Please let me know if there is any process or requirement for adding wallet onto your service.

I suggest that you get in touch with @Chef-Chungus to discuss about it. Obviously, we only add a wallet if there is a high demande from our community.

**Comment by paromix** [comment]
> > > We don't add wallets on demand like this.
> > 
> > 
> > Hi @RabbitDoge
> > My name is Minho Yoo, Chief Strategy Officer at D'CENT wallet. Thanks for your prompt response.
> > Please let me know if there is any process or requirement for adding wallet onto your service.
> 
> I suggest that you get in touch with @Chef-Chungus to discuss about it. Obviously, we only add a wallet if there is a high demande from our community.

Thanks for your reply!
Hi @Chef-Chungus , I'd like to discuss on what is needed to add D'CENT wallet onto PancakeSwap. Please let me know what is the next steps for discussing.
Thanks!

**Comment by paromix** [comment]
Hi @Chef-Chungus & @RabbitDoge
Many of D'CENT wallet's users are based in Korea. They asked us how to use PancakeSwap with D'CENT wallet. Of cource, we give the guidance to them, but it would be better if there is a button on PancakeSwap site to connect with D'CENT wallet. I'd like to discuss about it with you.
Thanks.

**Pull request closed without merging**
