### PR TITLE
feat(token-list): Update the BTT Token info.

### PR DESCRIPTION
**Pull request by Benson0224**
[x] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-uikit/blob/master/CONTRIBUTING.md) first
[x] If your PR is work in progress, open it as `draft`
[x] Before requesting a review, all the checks need to pass
[x] Explain what your PR does

Due to BTT Redenomination on Dec 6, 2021, the BTT Token needs to update.  Main Changes are below: 
1. Since the original BTT was re-named as BTTOLD, change the old BTT token to BTTOLD in "pancakeswap-extended" list.  
2. Add new BTT Token as New BTT trading pair was also launched on pancakeswap with $9.75M liquidity. https://pancakeswap.finance/info/token/0x352cb5e19b12fc216548a2677bd0fce83bae434b 

With BitTorrent Chain's cross-chain interoperability protocol, BTT is now available on BSC, ETH, and BTTC. below are the contract Address info, you can also find the latest info from BTTC websites. https://wallet.bt.io/mapping 
1. BTT on BSC: https://bscscan.com/token/0x352Cb5E19b12FC216548a2677bD0fce83BaE434B
2. BTT on BTTC: https://bttcscan.com/token/0x0000000000000000000000000000000000001010 
3. BTT on ETH: https://etherscan.io/token/0xc669928185dbce49d2230cc9b0979be6dc797957 

Please refer to more detail of the BTT Redenomination here : https://bttc.zendesk.com/hc/en-us/articles/4409343014937

### CODE REVIEW

**Comment by Benson0224** [comment]
@Chef-Cheems  @chef-jojo  Please kindly help to review this PR, thanks.

**Comment by Benson0224** [comment]
@chef-jojo  Seems my commit message does not meet the requirement, i just updated my commit message, please help to review it again, thanks.

**Comment by Benson0224** [comment]
my apology, updated the commit message again due to CI failing.  please help to review. thanks.

**Review by chef-jojo — APPROVED** [review]

**Comment by chef-jojo** [comment]
@Benson0224 nvm, it's good to go. Thanks for the pr.

**Pull request merged**
