### PR TITLE
fix: Put shadow under the bunny head of slider component

### PR DESCRIPTION
**Pull request by memoyil**

### CODE REVIEW

**Comment by memoyil** [comment]
@Chef-Chungus Ready to merge

**Review by hachiojidev — COMMENTED** [review]
Can you please send us a screenshot of the changes.

**Comment by memoyil** [comment]
@hachiojidev 

image

image

image

image

**Comment by Chef-Chungus** [comment]
@memoyil looks like the bunny head/shadow is getting cropped
image

**Comment by RabbitDoge** [comment]
Does this come from the figma ?

**Comment by memoyil** [comment]
@Chef-Chungus  @hachiojidev Should be ok now

image

image

image

image

**Comment by Chef-Chungus** [comment]
@RabbitDoge @hachiojidev looks good for me

**Review by RabbitDoge — APPROVED** [review]

**Pull request merged**
