### PR TITLE
fix: :fire: UI updates: button click animation, menu closing fix, men…

### PR DESCRIPTION
**Pull request by canllama**
- button press animation.
- Fixed text getting cutoff or stacked during side panel closing.
- Added missing transition to body for menu opening

### CODE REVIEW

**Comment by memoyil** [comment]
Can you share the differences visually?

**Comment by canllama** [comment]
the button changes are straight forward, adding a lil animation (can see in the storybook)

the panel fixes you can see the differences below during the **pushing animation** . You can see the differences below 

pancake diff

Also previous the panel sliding out had an animation, but the body of the page didn't. now they are both synchronised with the same time and transition function

**Comment by canllama** [comment]
Added a cute blink animation when hovering over the logo in the header
logo-blink

**Review by hachiojidev — CHANGES_REQUESTED** [review]
Thank you for submitting this. I did build it locally and do not see the bunny blinking when I hover the logo. Am I missing something?

I do like the button press animation. I am going to send a preview to the designer and see what he thinks before merging this.

**Comment by canllama** [comment]
Added the missing className for the Desktop logo :)

**Review by hachiojidev — APPROVED** [review]

**Pull request merged**
